spring:
  profiles:
    include: secret

  datasource:
    url:
    username:
    password:
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        format_sql:
        dialect:
  #    show-sql: true

  jwt:
    header:
    secret:
    access-token-validity-in-seconds :
    refresh-token-validity-in-seconds :

  data:
    redis:
      host:
      port:

logging.level:
  org.hibernate.SQL:

aes:
  secret-key: